'use client'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { TrashIcon, PencilIcon } from '@heroicons/react/24/solid'
import supabase from '@/utils/supabase'
import useStore from '@/store'
