import './globals.css'
import { LINE_Seed_JP } from '@/app/styles/fonts/fonts'
import NavBar from '@/app/components/nav-bar'

export const metadata = {
  title: 'Next.js 13',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${LINE_Seed_JP.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
